services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.10.7
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker/volumes/jellyfin/config:/config
      - /docker/volumes/media/finished/shows:/data/shows
      - /docker/volumes/media/finished/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    profiles:
      - jellyfin
      - media
  transmission:
    image: lscr.io/linuxserver/transmission:4.0.6
    container_name: transmission
    env_file: .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
    volumes:
      - /docker/volumes/transmission/config:/config
      - /docker/volumes/media/pending:/downloads/incomplete
      - /docker/volumes/media/finished/movies:/downloads/complete/movies
      - /docker/volumes/media/finished/shows:/downloads/complete/shows
      - /docker/volumes/archive:/downloads/complete/archive
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    profiles:
      - transmission
      - media
