services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.10.7
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ~/.jellyfin/config:/config
      - ~/media/finished/shows:/data/shows
      - ~/media/finished/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
  transmission:
    image: lscr.io/linuxserver/transmission:4.0.6
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - USER=${U}
      - PASS=${P}
    volumes:
      - ~/.transmission/config:/config
      - ~/media/pending:/downloads/incomplete
      - ~/media/finished/movies:/downloads/complete/movies
      - ~/media/finished/shows:/downloads/complete/shows
      - ~/archive:/downloads/complete/archive
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
